#FROM node:lts-alpine
FROM --platform=linux/arm64 node:lts
WORKDIR /app

ENV NX_PROD true
ENV NX_SERVER_ADDRESS SECRET
ENV NX_EXPRESS_PORT 3000
ENV NX_SOCKET_PORT 3001
ENV NX_CREDENTIALS SECRET
ENV NX_CALENDAR_IDS SECRET
ENV NX_DMI_API_KEY SECRET
ENV NX_UNSPLASH_API_KEY SECRET
COPY dist .
COPY package*.json ./
RUN npm install
CMD ["node", "server/main.js"]
EXPOSE 3000 3001
